{
 "title": "SMPP Clients",
 "tags": [ "smppclients-jasmin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30m",
 "templating": {
  "list": [
   {
    "name": "cid",
    "label": "SMPPClient",
    "query": {
     "query": "label_values(smppc_connected_count, cid)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(smppc_throttling_error_count{cid=\"$cid\"}[$__rate_interval])",
     "legendFormat": "Throttling"
    },
    {
     "expr": "rate(smppc_interceptor_error_count{cid=\"$cid\"}[$__rate_interval])",
     "legendFormat": "Interception"
    },
    {
     "expr": "rate(smppc_other_submit_error_count{cid=\"$cid\"}[$__rate_interval])",
     "legendFormat": "Other"
    }
   ]
  },
  {
   "title": "Bound sessions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smppc_bound_count{cid=\"$cid\"}",
     "legendFormat": "SubmitSm"
    }
   ]
  },
  {
   "title": "Messaging queue",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages{queue=\"submit.sm.$cid\"}",
     "legendFormat": "SubmitSm"
    }
   ]
  },
  {
   "title": "Received DLRs (jasmin)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages{queue=\"DLRLookup-main\"}",
     "legendFormat": "DLRs"
    }
   ]
  },
  {
   "title": "Enqueued DLRs (jasmin)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages{queue=\"dlr_thrower\"}",
     "legendFormat": "DLRs"
    }
   ]
  },
  {
   "title": "Disconnection counter",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smppc_disconnected_count{cid=\"$cid\"}",
     "legendFormat": "SubmitSm"
    }
   ]
  },
  {
   "title": "Queue consumers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rabbitmq_queue_consumers{queue=\"submit.sm.$cid\"}",
     "legendFormat": "Consulers"
    }
   ]
  },
  {
   "title": "Delivery rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(rabbitmq_channel_messages_delivered_ack_total{queue=\"submit.sm.$cid\"}[$__rate_interval])",
     "legendFormat": "Consulers"
    }
   ]
  },
  {
   "title": "Re-delivery rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(rabbitmq_channel_messages_redelivered_total{queue=\"submit.sm.$cid\"}[$__rate_interval])",
     "legendFormat": "Consulers"
    }
   ]
  },
  {
   "title": "Messaging rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(smppc_submit_sm_request_count{cid=\"$cid\"}[$__rate_interval])",
     "legendFormat": "Submit requests"
    },
    {
     "expr": "rate(smppc_submit_sm_count{cid=\"$cid\"}[$__rate_interval])",
     "legendFormat": "Submits"
    },
    {
     "expr": "rate(smppc_deliver_sm_count{cid=\"$cid\"}[$__rate_interval])",
     "legendFormat": "DeliverSm's"
    },
    {
     "expr": "rate(smppc_data_sm_count{cid=\"$cid\"}[$__rate_interval])",
     "legendFormat": "DataSm's"
    }
   ]
  }
 ]
}